package address.geolocation.com.geo.gateway.database.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
@With
@Getter
@Setter
@Builder
@DynamoDBTable(tableName = "Address")
public class AddressEntity {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String id;

    @DynamoDBAttribute
    @NotNull
    @NotEmpty(message = "cidade não pode estar vazia")
    public String city;

    @DynamoDBAttribute
    @NotNull
    @NotEmpty(message = "bairro não pode estar vazio")
    public String neighbourhood;

    @DynamoDBAttribute
    @NotNull
    @NotEmpty(message = "rua não pode estar vazia")
    public String streetName;

    @DynamoDBAttribute
    @NotNull
    @NotEmpty(message = "número não pode estar vazio")
    public String number;

    @DynamoDBAttribute
    public String complement;

    @DynamoDBAttribute
    @NotNull
    @NotEmpty(message = "estado não pode estar vazio")
    public String state;

    @DynamoDBAttribute
    @NotNull
    @NotEmpty(message = "país não pode estar vazio")
    public String country;

    @DynamoDBAttribute
    @NotNull
    @NotEmpty(message = "cep não pode estar vazio")
    public String zipCode;

    @DynamoDBAttribute
    public String latitude;

    @DynamoDBAttribute
    public String longitude;

}
